version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pramaan-ai-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pramaansecurepassword2026
      POSTGRES_DB: pramaan_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pramaan-ai-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:pramaansecurepassword2026@db:5432/pramaan_db?schema=public
      - SECRET_KEY=super-secret-pramaan-ai-security-hash-key-2026
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pramaan-ai-frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
